### ISSUE TITLE
Cant pick DanishBits as a tracker

### ISSUE THREAD

**Issue by Titte95** [cardigann/cardigann#166]
Can see cardigann is now supporting the private tracker DanishBits, but i cant choose it as an option when i've installed cardigann :(

**Comment by darkcloud784** [comment]
You may need to add the definition manually but copying the .yml file to the definitions folder. Alternatively you can try the edge build to see if its been added to the installer. Just because its listed on the github source doesn't mean its build into the installer or updater yet as they are hosted and added separately. I had to do this with funfile when they added it as an indexer.

**Comment by lxt2** [comment]
What version are you running @Titte95? If you are running on the `edge` build, you should have access to all the new trackers.
